export const TestData = {
    VALID_SEARCH_TERM: 'CCTV',
    INVALID_SEARCH_TERM: 'XXXXNORESULTSXXXX123456789',
    EXPECTED_MIN_CAMERAS: 1,
    MAX_PAGE_LOAD_TIME: 5000,
    MAX_SEARCH_TIME: 3000,
};
